#!/bin/sh /etc/rc.common
# Copyright (C) 2025 OpenWrt.org

START=95
STOP=15

USE_PROCD=1
PROG=/usr/bin/openwrt_vsim_client.py

start_service() {
	procd_open_instance
	procd_set_param command python3 "$PROG"
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}

service_triggers() {
	procd_add_config_trigger "config.change" "vsim_client" /etc/init.d/vsim_client reload
}